import type { Locale } from "@shi/game-core";

export type AudioUiKey = keyof typeof audioUi.en;

export const audioUi = {
  en: { sound: "Sound", soundOn: "Sound on", soundOff: "Sound off", title: "Soundscape", intro: "Rain and decision cues. Sound never carries exclusive information.", enable: "Enable sound", ambience: "Rain ambience", effects: "Decision cues", preview: "Preview cue", off: "Sound is off.", armed: "Sound will start with your next action.", starting: "Starting sound…", ready: "Sound is ready.", unsupported: "This browser cannot play the soundscape.", error: "Sound could not start.", review: "Engineering preview · human listening review pending" },
  ar: { sound: "الصوت", soundOn: "الصوت مفعّل", soundOff: "الصوت متوقف", title: "المشهد الصوتي", intro: "مطر وإشارات للقرارات. لا ينقل الصوت أي معلومة حصرية.", enable: "تفعيل الصوت", ambience: "أجواء المطر", effects: "إشارات القرارات", preview: "معاينة الإشارة", off: "الصوت متوقف.", armed: "سيبدأ الصوت مع الإجراء التالي.", starting: "جارٍ تشغيل الصوت…", ready: "الصوت جاهز.", unsupported: "لا يستطيع هذا المتصفح تشغيل المشهد الصوتي.", error: "تعذر تشغيل الصوت.", review: "معاينة هندسية · المراجعة البشرية للاستماع معلّقة" },
  de: { sound: "Ton", soundOn: "Ton an", soundOff: "Ton aus", title: "Klangbild", intro: "Regen und Entscheidungssignale. Ton vermittelt nie exklusive Informationen.", enable: "Ton einschalten", ambience: "Regenatmosphäre", effects: "Entscheidungssignale", preview: "Signal anhören", off: "Ton ist aus.", armed: "Ton startet bei der nächsten Aktion.", starting: "Ton wird gestartet…", ready: "Ton ist bereit.", unsupported: "Dieser Browser kann das Klangbild nicht wiedergeben.", error: "Ton konnte nicht gestartet werden.", review: "Technische Vorschau · menschliche Hörprüfung ausstehend" },
  es: { sound: "Sonido", soundOn: "Sonido activo", soundOff: "Sonido desactivado", title: "Paisaje sonoro", intro: "Lluvia y señales de decisión. El sonido nunca contiene información exclusiva.", enable: "Activar sonido", ambience: "Ambiente de lluvia", effects: "Señales de decisión", preview: "Probar señal", off: "El sonido está desactivado.", armed: "El sonido comenzará con tu próxima acción.", starting: "Iniciando sonido…", ready: "El sonido está listo.", unsupported: "Este navegador no puede reproducir el paisaje sonoro.", error: "No se pudo iniciar el sonido.", review: "Vista previa técnica · revisión auditiva humana pendiente" },
  fr: { sound: "Son", soundOn: "Son activé", soundOff: "Son coupé", title: "Paysage sonore", intro: "Pluie et signaux de décision. Le son ne porte jamais d’information exclusive.", enable: "Activer le son", ambience: "Ambiance de pluie", effects: "Signaux de décision", preview: "Écouter le signal", off: "Le son est coupé.", armed: "Le son commencera à la prochaine action.", starting: "Démarrage du son…", ready: "Le son est prêt.", unsupported: "Ce navigateur ne peut pas lire le paysage sonore.", error: "Le son n’a pas pu démarrer.", review: "Aperçu technique · écoute humaine en attente" },
  ja: { sound: "サウンド", soundOn: "サウンド オン", soundOff: "サウンド オフ", title: "サウンドスケープ", intro: "雨音と決断の合図。音だけで伝える情報はありません。", enable: "サウンドを有効にする", ambience: "雨の環境音", effects: "決断の合図", preview: "合図を試聴", off: "サウンドはオフです。", armed: "次の操作でサウンドが始まります。", starting: "サウンドを開始中…", ready: "サウンドの準備ができました。", unsupported: "このブラウザーではサウンドスケープを再生できません。", error: "サウンドを開始できませんでした。", review: "技術プレビュー · 人による試聴確認待ち" },
  ko: { sound: "사운드", soundOn: "사운드 켜짐", soundOff: "사운드 꺼짐", title: "사운드스케이프", intro: "빗소리와 결단 신호입니다. 소리만으로 전달되는 정보는 없습니다.", enable: "사운드 켜기", ambience: "빗소리 환경음", effects: "결단 신호", preview: "신호 미리 듣기", off: "사운드가 꺼져 있습니다.", armed: "다음 조작에서 사운드가 시작됩니다.", starting: "사운드 시작 중…", ready: "사운드가 준비되었습니다.", unsupported: "이 브라우저에서는 사운드스케이프를 재생할 수 없습니다.", error: "사운드를 시작하지 못했습니다.", review: "엔지니어링 미리보기 · 사람의 청취 검토 대기" },
  ru: { sound: "Звук", soundOn: "Звук включён", soundOff: "Звук выключен", title: "Звуковая среда", intro: "Дождь и сигналы решений. Звук никогда не передаёт уникальную информацию.", enable: "Включить звук", ambience: "Шум дождя", effects: "Сигналы решений", preview: "Проверить сигнал", off: "Звук выключен.", armed: "Звук начнётся при следующем действии.", starting: "Запуск звука…", ready: "Звук готов.", unsupported: "Этот браузер не может воспроизвести звуковую среду.", error: "Не удалось запустить звук.", review: "Инженерная версия · требуется прослушивание человеком" },
  vi: { sound: "Âm thanh", soundOn: "Đã bật âm thanh", soundOff: "Đã tắt âm thanh", title: "Không gian âm thanh", intro: "Tiếng mưa và tín hiệu quyết định. Âm thanh không bao giờ chứa thông tin riêng biệt.", enable: "Bật âm thanh", ambience: "Không khí mưa", effects: "Tín hiệu quyết định", preview: "Nghe thử tín hiệu", off: "Âm thanh đang tắt.", armed: "Âm thanh sẽ bắt đầu khi bạn thao tác tiếp.", starting: "Đang khởi động âm thanh…", ready: "Âm thanh đã sẵn sàng.", unsupported: "Trình duyệt này không thể phát không gian âm thanh.", error: "Không thể khởi động âm thanh.", review: "Bản xem trước kỹ thuật · đang chờ người nghe đánh giá" },
  "zh-Hans": { sound: "声音", soundOn: "声音已开", soundOff: "声音已关", title: "声音景观", intro: "雨声与决策提示音。声音不承载任何独占信息。", enable: "启用声音", ambience: "雨夜环境声", effects: "决策提示音", preview: "试听提示音", off: "声音已关闭。", armed: "声音将在下一次操作时开始。", starting: "正在启动声音…", ready: "声音已就绪。", unsupported: "此浏览器无法播放声音景观。", error: "声音无法启动。", review: "工程预览 · 等待真人听审" },
  "zh-Hant": { sound: "聲音", soundOn: "聲音已開", soundOff: "聲音已關", title: "聲音景觀", intro: "雨聲與決策提示音。聲音不承載任何獨佔資訊。", enable: "啟用聲音", ambience: "雨夜環境聲", effects: "決策提示音", preview: "試聽提示音", off: "聲音已關閉。", armed: "聲音將在下一次操作時開始。", starting: "正在啟動聲音…", ready: "聲音已就緒。", unsupported: "此瀏覽器無法播放聲音景觀。", error: "聲音無法啟動。", review: "工程預覽 · 等待真人聽審" },
} satisfies Record<Locale, Record<string, string>>;

export const translateAudio = (locale: Locale, key: AudioUiKey): string => audioUi[locale][key];
