import type { Locale } from "@shi/game-core";

export type UiKey = keyof typeof ui.en;

export const localeNames: Record<Locale, string> = {
  en: "English",
  ar: "العربية",
  de: "Deutsch",
  es: "Español",
  fr: "Français",
  ja: "日本語",
  ko: "한국어",
  ru: "Русский",
  vi: "Tiếng Việt",
  "zh-Hans": "简体中文",
  "zh-Hant": "繁體中文",
};

export const ui = {
  en: {
    begin: "Enter the rain", continue: "Continue", newGame: "New chronicle", chapter: "Playable pre-alpha · Chapter I",
    opening: "Power is not a possession. It is the shape made by people, terrain, time, and belief.",
    openingNote: "A strategic narrative set during the collapse of Qin. Historical record and dramatic reconstruction are marked separately.",
    grain: "Grain", trust: "Trust", momentum: "Momentum", people: "People", danger: "Exposure",
    strategicState: "Strategic state", record: "Record", sources: "Sources", sourceBasis: "Historical basis",
    choice: "Choose your shape", intent: "Intent", consequence: "Likely consequence", principle: "Strategic reading",
    turn: "Decision", of: "of", save: "Saved locally", restart: "Restart chapter", close: "Close", openSources: "Open source ledger",
    reconstruction: "Dramatic reconstruction", later: "Later compilation", primary: "Classical strategy text",
    locked: "Requires", complete: "Chapter complete", failed: "The network broke", captured: "State pursuit closed around the column.", scattered: "The movement lost the people needed to continue.",
    endingWildfire: "Wildfire", endingRoots: "Deep Roots", endingWatchful: "Watchful Strategist", next: "Continue the chronicle",
    endingWildfireText: "You made momentum into a weapon. Chapter II will test whether speed can survive hunger and concentrated pursuit.",
    endingRootsText: "You made consent into infrastructure. Chapter II will test whether a wide network can act before it is divided.",
    endingWatchfulText: "You preserved information and options. Chapter II will bring the emerging powers of Pei and Kuaiji into view.",
    historyEmpty: "Your decisions will be impressed here like marks in wet clay.", reducedMotion: "Reduce motion", language: "Language", pressureForecast: "Pressure forecast", pressureResponse: "The position answers", keyboardHint: "Shift+1–3 choose · Alt+S sources · Alt+R record · Esc close",
  },
  ar: {
    begin: "ادخل المطر", continue: "متابعة", newGame: "سجل جديد", chapter: "نسخة أولية قابلة للعب · الفصل الأول",
    opening: "القوة ليست ملكية؛ إنها الهيئة التي يصنعها الناس والأرض والوقت والاعتقاد.", openingNote: "سرد استراتيجي عند انهيار تشين. تُفصل المصادر التاريخية عن البناء الدرامي.",
    grain: "المؤن", trust: "الثقة", momentum: "الزخم", people: "الناس", danger: "الانكشاف", strategicState: "الوضع الاستراتيجي", record: "السجل", sources: "المصادر", sourceBasis: "الأساس التاريخي", choice: "اختر هيئتك", intent: "القصد", consequence: "النتيجة المحتملة", principle: "القراءة الاستراتيجية", turn: "قرار", of: "من", save: "حُفظ محليًا", restart: "إعادة الفصل", close: "إغلاق", openSources: "فتح سجل المصادر", reconstruction: "بناء درامي", later: "مصنّف لاحق", primary: "نص استراتيجي كلاسيكي", locked: "يتطلب", complete: "اكتمل الفصل", failed: "انكسرت الشبكة", captured: "أطبق مطاردو الدولة على القافلة.", scattered: "فقدت الحركة من تحتاج إليهم للاستمرار.", endingWildfire: "نار البراري", endingRoots: "جذور عميقة", endingWatchful: "الاستراتيجي المترقّب", next: "متابعة السجل", endingWildfireText: "حوّلت الزخم إلى سلاح. سيختبر الفصل الثاني إن كانت السرعة تصمد أمام الجوع والمطاردة.", endingRootsText: "حوّلت الرضا إلى بنية. سيختبر الفصل الثاني قدرة الشبكة على الفعل قبل انقسامها.", endingWatchfulText: "حفظت المعلومات والخيارات. سيكشف الفصل الثاني قوى بِي وكوايجي الصاعدة.", historyEmpty: "ستُطبع قراراتك هنا كعلامات في طين مبتل.", reducedMotion: "تقليل الحركة", language: "اللغة", pressureForecast: "توقّع الضغط", pressureResponse: "الموقف يجيب", keyboardHint: "Shift+1–3 للاختيار · Alt+S للمصادر · Alt+R للسجل · Esc للإغلاق",
  },
  de: {
    begin: "In den Regen", continue: "Fortsetzen", newGame: "Neue Chronik", chapter: "Spielbare Pre-Alpha · Kapitel I", opening: "Macht ist kein Besitz. Sie ist die Form, die Menschen, Gelände, Zeit und Glaube bilden.", openingNote: "Eine strategische Erzählung beim Zerfall Qins. Historischer Befund und dramatische Rekonstruktion sind getrennt markiert.", grain: "Getreide", trust: "Vertrauen", momentum: "Dynamik", people: "Menschen", danger: "Entdeckung", strategicState: "Strategische Lage", record: "Chronik", sources: "Quellen", sourceBasis: "Historische Grundlage", choice: "Wähle deine Form", intent: "Absicht", consequence: "Mögliche Folge", principle: "Strategische Lesart", turn: "Entscheidung", of: "von", save: "Lokal gespeichert", restart: "Kapitel neu starten", close: "Schließen", openSources: "Quellenbuch öffnen", reconstruction: "Dramatische Rekonstruktion", later: "Spätere Kompilation", primary: "Klassischer Strategietext", locked: "Benötigt", complete: "Kapitel abgeschlossen", failed: "Das Netz zerbrach", captured: "Die Verfolger des Staates schlossen den Zug ein.", scattered: "Der Bewegung fehlten die Menschen zum Weitermachen.", endingWildfire: "Lauffeuer", endingRoots: "Tiefe Wurzeln", endingWatchful: "Wachsamer Stratege", next: "Chronik fortsetzen", endingWildfireText: "Du hast Dynamik zur Waffe gemacht. Kapitel II prüft, ob Tempo Hunger und Verfolgung übersteht.", endingRootsText: "Du hast Zustimmung zur Infrastruktur gemacht. Kapitel II prüft, ob das Netz vor seiner Spaltung handeln kann.", endingWatchfulText: "Du hast Wissen und Möglichkeiten bewahrt. Kapitel II bringt Pei und Kuaiji ins Blickfeld.", historyEmpty: "Deine Entscheidungen werden hier wie Spuren in nassem Ton geprägt.", reducedMotion: "Bewegung reduzieren", language: "Sprache", pressureForecast: "Druckanzeichen", pressureResponse: "Die Lage antwortet", keyboardHint: "Shift+1–3 wählen · Alt+S Quellen · Alt+R Chronik · Esc schließen",
  },
  es: {
    begin: "Entrar en la lluvia", continue: "Continuar", newGame: "Nueva crónica", chapter: "Prealfa jugable · Capítulo I", opening: "El poder no se posee. Es la forma creada por personas, terreno, tiempo y creencias.", openingNote: "Una narrativa estratégica durante el colapso de Qin. Se distinguen registro histórico y reconstrucción dramática.", grain: "Grano", trust: "Confianza", momentum: "Impulso", people: "Pueblo", danger: "Exposición", strategicState: "Estado estratégico", record: "Crónica", sources: "Fuentes", sourceBasis: "Base histórica", choice: "Elige tu forma", intent: "Intención", consequence: "Consecuencia probable", principle: "Lectura estratégica", turn: "Decisión", of: "de", save: "Guardado local", restart: "Reiniciar capítulo", close: "Cerrar", openSources: "Abrir registro de fuentes", reconstruction: "Reconstrucción dramática", later: "Compilación posterior", primary: "Texto estratégico clásico", locked: "Requiere", complete: "Capítulo completo", failed: "La red se quebró", captured: "La persecución estatal cercó a la columna.", scattered: "El movimiento perdió a la gente necesaria para continuar.", endingWildfire: "Incendio", endingRoots: "Raíces profundas", endingWatchful: "Estratega vigilante", next: "Continuar la crónica", endingWildfireText: "Convertiste el impulso en arma. El capítulo II probará si la velocidad sobrevive al hambre y la persecución.", endingRootsText: "Convertiste el consentimiento en infraestructura. El capítulo II probará si una red amplia actúa antes de dividirse.", endingWatchfulText: "Conservaste información y opciones. El capítulo II mostrará los poderes emergentes de Pei y Kuaiji.", historyEmpty: "Tus decisiones quedarán aquí como marcas en arcilla húmeda.", reducedMotion: "Reducir movimiento", language: "Idioma", pressureForecast: "Señal de presión", pressureResponse: "La posición responde", keyboardHint: "Shift+1–3 elegir · Alt+S fuentes · Alt+R crónica · Esc cerrar",
  },
  fr: {
    begin: "Entrer dans la pluie", continue: "Continuer", newGame: "Nouvelle chronique", chapter: "Pré-alpha jouable · Chapitre I", opening: "Le pouvoir n'est pas un bien. C'est la forme créée par les êtres, le terrain, le temps et la croyance.", openingNote: "Un récit stratégique lors de l'effondrement des Qin. Sources historiques et reconstruction dramatique sont distinguées.", grain: "Grain", trust: "Confiance", momentum: "Élan", people: "Peuple", danger: "Exposition", strategicState: "État stratégique", record: "Chronique", sources: "Sources", sourceBasis: "Base historique", choice: "Choisissez votre forme", intent: "Intention", consequence: "Conséquence probable", principle: "Lecture stratégique", turn: "Décision", of: "sur", save: "Sauvegarde locale", restart: "Recommencer", close: "Fermer", openSources: "Ouvrir le registre des sources", reconstruction: "Reconstruction dramatique", later: "Compilation tardive", primary: "Texte stratégique classique", locked: "Requiert", complete: "Chapitre terminé", failed: "Le réseau s'est rompu", captured: "La poursuite de l'État a encerclé la colonne.", scattered: "Le mouvement a perdu les personnes nécessaires pour continuer.", endingWildfire: "Feu de brousse", endingRoots: "Racines profondes", endingWatchful: "Stratège vigilant", next: "Poursuivre la chronique", endingWildfireText: "Vous avez fait de l'élan une arme. Le chapitre II testera si la vitesse survit à la faim et à la poursuite.", endingRootsText: "Vous avez fait du consentement en infrastructure. Le chapitre II testera si le réseau agit avant d'être divisé.", endingWatchfulText: "Vous avez préservé informations et options. Le chapitre II dévoilera Pei et Kuaiji.", historyEmpty: "Vos décisions s'imprimeront ici comme des marques dans l'argile humide.", reducedMotion: "Réduire le mouvement", language: "Langue", pressureForecast: "Signe de pression", pressureResponse: "La position répond", keyboardHint: "Shift+1–3 choisir · Alt+S sources · Alt+R chronique · Échap fermer",
  },
  ja: {
    begin: "雨の中へ", continue: "続ける", newGame: "新しい記録", chapter: "プレイ可能プレアルファ · 第一章", opening: "力は所有物ではない。人・地形・時・信が織りなす形である。", openingNote: "秦崩壊期の戦略物語。史料と劇的再構成を明確に区別します。", grain: "兵糧", trust: "信頼", momentum: "勢い", people: "民衆", danger: "露見", strategicState: "戦略状態", record: "記録", sources: "史料", sourceBasis: "史料的根拠", choice: "形勢を選ぶ", intent: "意図", consequence: "予想される結果", principle: "戦略的解釈", turn: "決断", of: "/", save: "端末に保存済み", restart: "章をやり直す", close: "閉じる", openSources: "史料台帳を開く", reconstruction: "劇的再構成", later: "後世の編纂", primary: "古典戦略書", locked: "必要条件", complete: "章を完了", failed: "網が崩れた", captured: "国家の追手が隊列を包囲した。", scattered: "運動を続けるための人々を失った。", endingWildfire: "野火", endingRoots: "深い根", endingWatchful: "観勢の策士", next: "記録を続ける", endingWildfireText: "勢いを武器にした。第二章では速度が飢えと追撃に耐えられるかが試される。", endingRootsText: "同意を基盤に変えた。第二章では広い網が分断前に動けるかが試される。", endingWatchfulText: "情報と選択肢を守った。第二章では沛と会稽の新勢力が姿を現す。", historyEmpty: "決断は濡れた粘土の跡のようにここへ刻まれます。", reducedMotion: "動きを減らす", language: "言語", pressureForecast: "圧力の兆し", pressureResponse: "局面の応手", keyboardHint: "Shift+1〜3 選択 · Alt+S 史料 · Alt+R 記録 · Esc 閉じる",
  },
  ko: {
    begin: "빗속으로", continue: "계속", newGame: "새 기록", chapter: "플레이 가능 프리알파 · 제1장", opening: "힘은 소유물이 아니다. 사람과 지형, 시간과 믿음이 만드는 형세다.", openingNote: "진 제국 붕괴기의 전략 서사. 역사 기록과 극적 재구성을 구분합니다.", grain: "군량", trust: "신뢰", momentum: "기세", people: "민심", danger: "노출", strategicState: "전략 상태", record: "기록", sources: "사료", sourceBasis: "역사적 근거", choice: "형세를 선택하라", intent: "의도", consequence: "예상 결과", principle: "전략 해설", turn: "결정", of: "/", save: "기기에 저장됨", restart: "장 다시 시작", close: "닫기", openSources: "사료 장부 열기", reconstruction: "극적 재구성", later: "후대 편찬", primary: "고전 전략서", locked: "필요", complete: "장 완료", failed: "연결망 붕괴", captured: "국가의 추격대가 행렬을 포위했다.", scattered: "운동을 이어갈 사람들을 잃었다.", endingWildfire: "들불", endingRoots: "깊은 뿌리", endingWatchful: "관망하는 전략가", next: "기록 계속하기", endingWildfireText: "기세를 무기로 만들었다. 제2장은 속도가 굶주림과 추격을 견디는지 시험한다.", endingRootsText: "동의를 기반 시설로 만들었다. 제2장은 넓은 연결망이 분열 전에 움직이는지 시험한다.", endingWatchfulText: "정보와 선택지를 보존했다. 제2장에서 패와 회계의 새 세력이 드러난다.", historyEmpty: "결정은 젖은 진흙 자국처럼 이곳에 새겨집니다.", reducedMotion: "움직임 줄이기", language: "언어", pressureForecast: "압력 예고", pressureResponse: "국면의 응수", keyboardHint: "Shift+1–3 선택 · Alt+S 사료 · Alt+R 기록 · Esc 닫기",
  },
  ru: {
    begin: "Войти под дождь", continue: "Продолжить", newGame: "Новая хроника", chapter: "Играбельная пре-альфа · Глава I", opening: "Власть — не вещь. Это форма, созданная людьми, местностью, временем и верой.", openingNote: "Стратегический рассказ о распаде Цинь. Источники отделены от художественной реконструкции.", grain: "Зерно", trust: "Доверие", momentum: "Порыв", people: "Люди", danger: "Раскрытие", strategicState: "Стратегическое положение", record: "Хроника", sources: "Источники", sourceBasis: "Историческая основа", choice: "Выберите форму", intent: "Замысел", consequence: "Вероятное следствие", principle: "Стратегическое чтение", turn: "Решение", of: "из", save: "Сохранено локально", restart: "Начать главу заново", close: "Закрыть", openSources: "Открыть реестр источников", reconstruction: "Художественная реконструкция", later: "Поздняя компиляция", primary: "Классический трактат", locked: "Требуется", complete: "Глава завершена", failed: "Сеть распалась", captured: "Государственная погоня окружила колонну.", scattered: "Движение потеряло людей, нужных для продолжения.", endingWildfire: "Степной пожар", endingRoots: "Глубокие корни", endingWatchful: "Бдительный стратег", next: "Продолжить хронику", endingWildfireText: "Вы превратили порыв в оружие. Глава II проверит, переживёт ли скорость голод и погоню.", endingRootsText: "Вы превратили согласие в инфраструктуру. Глава II проверит, успеет ли сеть действовать до раскола.", endingWatchfulText: "Вы сохранили сведения и варианты. Глава II покажет растущие силы Пэй и Куайцзи.", historyEmpty: "Решения отпечатаются здесь, как знаки на сырой глине.", reducedMotion: "Уменьшить движение", language: "Язык", pressureForecast: "Признак давления", pressureResponse: "Позиция отвечает", keyboardHint: "Shift+1–3 выбор · Alt+S источники · Alt+R хроника · Esc закрыть",
  },
  vi: {
    begin: "Bước vào mưa", continue: "Tiếp tục", newGame: "Biên niên mới", chapter: "Tiền alpha có thể chơi · Chương I", opening: "Quyền lực không phải vật sở hữu. Nó là thế do người, đất, thời và lòng tin tạo nên.", openingNote: "Truyện chiến lược thời Tần sụp đổ. Sử liệu và tái dựng kịch tính được ghi rõ riêng biệt.", grain: "Lương", trust: "Tín", momentum: "Thế", people: "Dân", danger: "Bại lộ", strategicState: "Thế cục", record: "Biên niên", sources: "Nguồn", sourceBasis: "Cơ sở lịch sử", choice: "Chọn thế", intent: "Ý định", consequence: "Hệ quả có thể", principle: "Luận giải chiến lược", turn: "Quyết định", of: "/", save: "Đã lưu trên máy", restart: "Chơi lại chương", close: "Đóng", openSources: "Mở sổ nguồn", reconstruction: "Tái dựng kịch tính", later: "Biên soạn đời sau", primary: "Binh thư cổ điển", locked: "Cần", complete: "Hoàn thành chương", failed: "Mạng lưới tan vỡ", captured: "Quân truy đuổi đã khép vòng quanh đoàn người.", scattered: "Phong trào mất những người cần để tiếp tục.", endingWildfire: "Lửa đồng", endingRoots: "Rễ sâu", endingWatchful: "Người quan thế", next: "Tiếp tục biên niên", endingWildfireText: "Bạn biến khí thế thành vũ khí. Chương II sẽ thử xem tốc độ có sống qua đói và truy đuổi.", endingRootsText: "Bạn biến đồng thuận thành hạ tầng. Chương II thử xem mạng lưới có hành động trước khi chia rẽ.", endingWatchfulText: "Bạn giữ được tin tức và lựa chọn. Chương II sẽ hé lộ thế lực ở Bái và Cối Kê.", historyEmpty: "Quyết định sẽ in tại đây như dấu trên đất sét ướt.", reducedMotion: "Giảm chuyển động", language: "Ngôn ngữ", pressureForecast: "Dấu hiệu áp lực", pressureResponse: "Thế cục đáp lại", keyboardHint: "Shift+1–3 chọn · Alt+S nguồn · Alt+R biên niên · Esc đóng",
  },
  "zh-Hans": {
    begin: "走入这场雨", continue: "继续旧局", newGame: "重开一卷", chapter: "可玩前期版本 · 第一章", opening: "势不是可以占有的东西。它是人、地、时与信念共同形成的形。", openingNote: "一部以秦帝国崩解为背景的策略叙事。史料与戏剧性重构会被明确区分。", grain: "粮", trust: "信", momentum: "势", people: "民", danger: "险", strategicState: "当前局势", record: "决策简牍", sources: "史料", sourceBasis: "史料依据", choice: "选择你的形势", intent: "意图", consequence: "可能后果", principle: "策略解读", turn: "决策", of: "/", save: "已保存于本机", restart: "重开本章", close: "合上", openSources: "打开史料簿", reconstruction: "戏剧性重构", later: "后世编纂", primary: "古典兵学文本", locked: "需要", complete: "本章完成", failed: "网络已断", captured: "秦吏追捕合围了队伍。", scattered: "队伍失去了继续行动所需的人。", endingWildfire: "野火", endingRoots: "深根", endingWatchful: "观势者", next: "继续书写", endingWildfireText: "你把声势变成了武器。第二章将检验速度能否挺过饥饿与集中追捕。", endingRootsText: "你把同意变成了基础设施。第二章将检验广阔网络能否在分裂前采取行动。", endingWatchfulText: "你保留了情报与选择。第二章将让沛县与会稽正在形成的力量进入视野。", historyEmpty: "你的选择会像湿泥上的刻痕一样留在这里。", reducedMotion: "减少动态", language: "语言", pressureForecast: "压力预兆", pressureResponse: "局势应手", keyboardHint: "Shift+1–3 选择 · Alt+S 史料 · Alt+R 记录 · Esc 合上",
  },
  "zh-Hant": {
    begin: "走入這場雨", continue: "繼續舊局", newGame: "重開一卷", chapter: "可玩前期版本 · 第一章", opening: "勢不是可以佔有的東西。它是人、地、時與信念共同形成的形。", openingNote: "一部以秦帝國崩解為背景的策略敘事。史料與戲劇性重構會被明確區分。", grain: "糧", trust: "信", momentum: "勢", people: "民", danger: "險", strategicState: "當前局勢", record: "決策簡牘", sources: "史料", sourceBasis: "史料依據", choice: "選擇你的形勢", intent: "意圖", consequence: "可能後果", principle: "策略解讀", turn: "決策", of: "/", save: "已儲存於本機", restart: "重開本章", close: "合上", openSources: "打開史料簿", reconstruction: "戲劇性重構", later: "後世編纂", primary: "古典兵學文本", locked: "需要", complete: "本章完成", failed: "網絡已斷", captured: "秦吏追捕合圍了隊伍。", scattered: "隊伍失去了繼續行動所需的人。", endingWildfire: "野火", endingRoots: "深根", endingWatchful: "觀勢者", next: "繼續書寫", endingWildfireText: "你把聲勢變成了武器。第二章將檢驗速度能否挺過飢餓與集中追捕。", endingRootsText: "你把同意變成了基礎設施。第二章將檢驗廣闊網絡能否在分裂前採取行動。", endingWatchfulText: "你保留了情報與選擇。第二章將讓沛縣與會稽正在形成的力量進入視野。", historyEmpty: "你的選擇會像濕泥上的刻痕一樣留在這裡。", reducedMotion: "減少動態", language: "語言", pressureForecast: "壓力預兆", pressureResponse: "局勢應手", keyboardHint: "Shift+1–3 選擇 · Alt+S 史料 · Alt+R 記錄 · Esc 合上",
  },
} satisfies Record<Locale, Record<string, string>>;

export const isRtl = (locale: Locale): boolean => locale === "ar";
export const translate = (locale: Locale, key: UiKey): string => ui[locale][key] ?? ui.en[key];
