import type { Locale } from "@shi/game-core";

interface GuideDetails {
  intro: string;
  move: string;
  reply: string;
}

export const guideDetails: Record<Locale, GuideDetails> = {
  en: { intro: "Every order resolves in six visible layers: your move, a commitment answer when due, authored pressure, pursuit posture, Qin’s method read, and the disclosed field condition.", move: "Select an order to open its complete strategic reading. Only Issue order commits it; selection never changes the campaign.", reply: "The reading discloses exact effects, method, commitments, and Qin’s current hit or miss. Every resolved delta is recorded separately." },
  ar: { intro: "يُحسم كل أمر في ست طبقات ظاهرة: حركتك، وجواب الالتزام عند استحقاقه، والضغط المؤلَّف، ووضع المطاردة، وقراءة تشين للأسلوب، وظرف الميدان المعلن.", move: "اختر أمرًا لفتح قراءته الاستراتيجية الكاملة. لا يُثبّته إلا «أصدر الأمر»؛ والاختيار وحده لا يغيّر الحملة.", reply: "تكشف القراءة الآثار الدقيقة والأسلوب والالتزامات وهل تصيب قراءة تشين الحالية أم تخطئ. يُسجّل كل تغيّر محسوم منفصلًا." },
  de: { intro: "Jeder Befehl wird in sechs sichtbaren Ebenen aufgelöst: dein Zug, eine fällige Antwort auf das Versprechen, verfasster Druck, Verfolgungslage, Qins Methodenanalyse und die angekündigte Feldbedingung.", move: "Wähle einen Befehl, um seine vollständige strategische Lesart zu öffnen. Erst Befehl erteilen legt ihn fest; die Auswahl verändert die Kampagne nie.", reply: "Die Lesart zeigt genaue Wirkungen, Methode, Versprechen und ob Qins aktuelle Analyse trifft oder verfehlt. Jede aufgelöste Änderung wird getrennt notiert." },
  es: { intro: "Cada orden se resuelve en seis capas visibles: tu movimiento, la respuesta a un compromiso cuando corresponda, la presión escrita, la postura de persecución, la lectura de método de Qin y la condición anunciada del terreno.", move: "Selecciona una orden para abrir su lectura estratégica completa. Solo Dar la orden la confirma; seleccionar nunca altera la campaña.", reply: "La lectura revela efectos exactos, método, compromisos y si el cálculo actual de Qin acierta o falla. Cada cambio resuelto queda registrado aparte." },
  fr: { intro: "Chaque ordre se résout en six couches visibles : votre coup, la réponse à un engagement lorsqu’elle est due, la pression écrite, le dispositif de poursuite, la lecture de méthode des Qin et la condition annoncée du terrain.", move: "Sélectionnez un ordre pour ouvrir sa lecture stratégique complète. Seul Donner l’ordre le confirme ; la sélection ne modifie jamais la campagne.", reply: "La lecture dévoile effets exacts, méthode, engagements et si l’analyse actuelle des Qin vise juste ou échoue. Chaque écart résolu est consigné séparément." },
  ja: { intro: "一つの命令は六つの可視層で決着する。自分の一手、必要な時の約束への応答、既定の圧力、追撃態勢、秦の手筋読み、そして予告された戦場条件だ。", move: "命令を選ぶと、完全な戦略的解釈が開く。確定するのは「命令を下す」だけで、選択だけでは戦況は変わらない。", reply: "解釈には正確な効果、手筋、約束、秦の現在の読みの的中・不的中が示される。決着した変化はすべて別に記録される。" },
  ko: { intro: "하나의 명령은 여섯 개의 보이는 층으로 결산된다. 나의 수, 때가 된 약속의 응답, 서술된 압력, 추격 태세, 진의 수법 판독, 그리고 예고된 전장 조건이다.", move: "명령을 선택하면 완전한 전략 해설이 열린다. ‘명령 내리기’만 확정하며, 선택만으로는 전황이 바뀌지 않는다.", reply: "해설은 정확한 효과와 수법, 약속, 진의 현재 판독이 적중하는지 빗나가는지를 밝힌다. 결산된 변화는 모두 따로 기록된다." },
  ru: { intro: "Каждый приказ разрешается в шести видимых слоях: ваш ход, ответ на обязательство, когда он требуется, заданное давление, состояние погони, разбор метода Цинь и объявленное условие поля.", move: "Выберите приказ, чтобы открыть полный стратегический разбор. Только Отдать приказ подтверждает его; выбор не меняет кампанию.", reply: "Разбор раскрывает точные последствия, метод, обязательства и попадание либо промах текущего расчёта Цинь. Каждое разрешённое изменение записывается отдельно." },
  vi: { intro: "Mỗi mệnh lệnh được kết toán qua sáu lớp hiển thị: nước đi, cách đáp cam kết khi đến hạn, áp lực soạn sẵn, thế truy đuổi, cách Tần đọc thủ pháp và điều kiện bàn thế đã báo.", move: "Chọn một mệnh lệnh để mở toàn bộ luận thế chiến lược. Chỉ Ban lệnh mới xác nhận; việc chọn không bao giờ làm đổi chiến dịch.", reply: "Luận thế công khai hiệu ứng chính xác, thủ pháp, cam kết và cách đọc hiện tại của Tần trúng hay trượt. Mọi thay đổi đã kết toán đều được ghi riêng." },
  "zh-Hans": { intro: "每道命令分六层明示结算：你的落子、到期的应诺、既定压力、追捕态势、秦吏手法识势，以及预先公开的局势条件。", move: "选择一道命令，打开完整的战略解读。只有“下达命令”才会落子；仅作选择绝不会改变战局。", reply: "解读会明示确切影响、战略手法、承诺，以及秦吏当前识势命中或落空。结算后的每层变化都会单独记录。" },
  "zh-Hant": { intro: "每道命令分六層明示結算：你的落子、到期的應諾、既定壓力、追捕態勢、秦吏手法識勢，以及預先公開的局勢條件。", move: "選擇一道命令，打開完整的戰略解讀。只有「下達命令」才會落子；僅作選擇絕不會改變戰局。", reply: "解讀會明示確切影響、戰略手法、承諾，以及秦吏當前識勢命中或落空。結算後的每層變化都會單獨記錄。" },
};
